sudo: required
language: node_js
node_js:
  - "6.9.1"

addons:
  postgresql: "9.5"
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

env:
  - CXX=g++-4.8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev

  - cd $TRAVIS_BUILD_DIR

  # Configure postgres
  - psql -c 'create database suitec_travis;' -U postgres
  - psql suitec_travis -c 'create extension pg_trgm;' -U postgres

script:
  - node_modules/.bin/gulp travis
