version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 6.15.1
    commands:
      - chmod 755 ./scripts/generate-build-stats.sh && ./scripts/generate-build-stats.sh
      - npm i -g npm@3.10.10
      - npm install
      - npm install -g bower
      - npm install -g gulp
  pre_build:
    commands:
      - echo "pre_build phase"
  build:
    commands:
      - ./node_modules/.bin/bower install --allow-root
      - ./node_modules/.bin/gulp build --allow-root
  post_build:
    commands:
      - echo "post_build phase"

artifacts:
  files:
    - '.ebextensions/*'
    - '.elasticbeanstalk/*'
    - '.gitignore'
    - '.npmrc'
    - '**/*'
